- name: Install Catalogue
  hosts: catalogue
  become: yes 
  tasks:
  - name: set up NPM sources
    ansible.builtin.shell: "https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: checking exists roboshop user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true

  #when: out.rc != 0 
  - name: create user roboshop
    when: out.rc != 0
    ansible.builtin.user: 
      name: roboshop

  - name: checl/ app directory exists or not 
    ansible.builtin.stat:
      path: /app
    register: directory          

  - name: print the directory stats
    ansible.builtin.debug:
      msg: "output: {{directory}}"

  - name: create directory  /app
    when: directory.stat.exists == 'false'
    ansible.builtin.file:
      path: /app
      state: directory    
