- name: Install user component
  hosts: user
  become: yes 
  tasks:
  - name: set up NPM sources
    ansible.builtin.shell: "https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: checking exists roboshop user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true

  #when: out.rc != 0 
  - name: create user roboshop
    when: out.rc != 0
    ansible.builtin.user: 
      name: roboshop

  - name: checl/ app directory exists or not 
    ansible.builtin.stat:
      path: /app
    register: directory          

  - name: print the directory stats
    ansible.builtin.debug:
      msg: "output: {{directory}}"

  - name: create directory  /app
    when: directory.stat.exists == False
    ansible.builtin.file:
      path: /app
      state: directory  

  - name: download user artifacts
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: extract user artifact
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app 
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install 
    args:
      chdir:  /app 

  - name: copy user.service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: demon reload
    ansible.builtin.systemd:
      daemon_reload: true  

  - name: copy mango.repo to yum.repos.d
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo 

  - name: Install Mongodb
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: load catlogue data into mongodb
    ansible.builtin.command: mongo --host 172.31.32.117 < /app/schema/user.js

  - name: restart and enable user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes   